type Margins = Record<string, number>
export const margins: Margins = {
  'Sales of hair extention/accessories': 22.52,
  Cosmetics: 21.11,
  'Sales of wood': 24.83,
  'Sales of Phone accessories': 21.76,
  'Sales of Tyres(General Automobile)': 20.42,
  'Sales of Trucks spare parts': 27.11,
  'Sales Agro-allied products': 21.33,
  'Sales of Baby Item': 20.11,
  'Aluminium profiles and accessories(windows/door/partitioning accessories)': 16.73,
  'Fabrication and sale of aluminium roofing sheets': 27.11,
  'Sales of Suspended Ceiling': 18.01,
  'Sales of POP': 24.47,
  'Sales of Plank': 20.73,
  'Sales of provision and grocery stores': 13.16,
  'Sales of Auto-paints': 22.57,
  'Sales of Iphone and accessories': 21.04,
  'Sales of Pharmaceutical products': 24.73,
  'Sales of Cellotape': 27.11,
  'Sales of fabric and textile materials': 21.39,
  'Sales of Palm Oil': 17.11,
  'Sale of alcoholic drinks': 12.12,
  'Sale of non-alcoholic drinks': 10.24,
  'Sales of assorted wines': 22.55,
  'Iron and steel rods': 13.46,
  'Water production/beverage drink': 27.11,
  'Sales of footwears': 13.43,
  'Haulage/Logistics': 80,
  'Cooking Gas/home accessories': 13.11,
  'Food chemicals': 9.3,
  'Production of paints	': 27.11,
  'Production and sale of polythene product': 27.11,
  'Building materials ( roofing felt )': 18.66,
  Hospital: 27.11,
  'School labouratory equipment': 25.11,
  'Automobile spare-parts': 27.11,
  'Building block production/inter-locking': 22.11,
  'Bakery/Confectionaries': 17.11,
  'Sale of PVC water pipes and accessories': 21.83,
  'Sales of Mobile phones': 23.11,
  'Butchers/sale of meat': 23.47,
  'Welding Service (Metal/Tanker fabrication/general)': 24.11,
  'Electrical home accessories': 17.25,
  'Printing Materials and printing press': 27.11,
  'Sales of clothings and boutique ( Shoes,shirts, etc)': 17.72,
  'Sale of industrial papers': 21.48,
  'Sales of Alubond sheet': 23.46,
  'General building matrials': 20.66,
  'Sales of cars': 24.87,
  'Sales of Laminated Wood/HDF/MDF Wood /plywood': 22.3,
  'Sales of Metal Scrap': 24.42,
  'Animal feeds': 12.3,
  'Sales of Iron and building material': 15.56,
  'Sales of electronics and Computer systems': 19.4,
  'Sales of Car engine': 19.07,
  'Sales of Electronics': 22.24,
  'Sales of frozen food': 12.81,
  'Mattress and pillow': 16.98,
  'Sales of electrical material': 26.11,
  'Sales of PMS ( Petroleum Product)': 11.89,
  'Sales recharge cards': 10.1,
  'Sales of rechargable and stationary': 20.64,
  'Sales of truck head and spare parts': 16.11,
  'Poultry farming/sale of egg/chicken feeds': 18.91,
  'Sales of industrial electric motor': 23.11,
  'Fabrication and sale of furnitures/embroidery/sewing': 27.11,
  'Sales of sesame seeds, cashew nuts and ginger': 14.8,
  'Sales of foodstufs( garri, rice, beans, yams, palm oil )': 15.8,
  'Sales of building doors (imported doors)': 24.46,
  'General  industrial chemicals': 24.76,
  'Tailoring materials': 21.36,
  'Hotel/hospitality': 80,
  'Production of tissue paper/disposable cup&plates': 25.11,
  'Ladies clothes': 20.11,
  'Medical & scientific equipment': 24.73,
  'Sales of bags': 24.06,
  'Sales of furniture': 21.27,
  'Production of furntures': 27.11,
  'Recycling/production of nylon': 27.11,
  'Traditional /herbal drugs': 25.59,
  'Bureau de-change': 8.48,
  'Sales padlocks and keys': 17.5,
  'Organic medicine/drugs': 24.69,
  School: 80,
  'Sales of jewelries': 26.24,
  'Generator/generator spare-parts': 26.11,
  'Production/sale of industrial printing inks/chemicals': 22.28,
  'Production/sale of chinchin': 23.36,
  'Sale of motorcycle spare/lubricants': 20.78,
  'Sales of rubber shoes': 19.18,
  'Sales of gift items ,stationeries and Household': 25.11,
  'Industrial kitchen equipment': 21.89,
  'Eatery/confectionery/Restaurant': 27.11,
  'Household and kitchen utensils': 26.37,
  'Rental services': 80,
  'Mats and centre rugs': 23.56,
  'Sales of Leather, sofa/cushion materials': 21.34,
  'Sales of water dispenser': 23.49,
  'Polythene/plastics products': 27.11,
  'Industrial machines': 27.11,
  'Sales of Solar panels': 25.11,
  'Sales of wristwatches': 25.31,
  'Sales of plumbing materials': 24.11,
  'production of food spices': 25.11,
  'production of hair extension/attachment': 23.11,
  'Sales of Glass and Accessories': 22.43,
  'Electric Transformers': 17.05,
  'Laptop and computer system': 18.29,
  'Production of edible oil': 12.11,
}

export const marginsArr = Object.entries(margins)
