/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as IndexImport } from './routes/index'
import { Route as AppApplayoutImport } from './routes/app/_applayout'
import { Route as AppApplayoutDashboardImport } from './routes/app/_applayout.dashboard'

// Create Virtual Routes

const AppImport = createFileRoute('/app')()

// Create/Update Routes

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppApplayoutRoute = AppApplayoutImport.update({
  id: '/_applayout',
  getParentRoute: () => AppRoute,
} as any)

const AppApplayoutDashboardRoute = AppApplayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AppApplayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/_applayout': {
      preLoaderRoute: typeof AppApplayoutImport
      parentRoute: typeof AppRoute
    }
    '/app/_applayout/dashboard': {
      preLoaderRoute: typeof AppApplayoutDashboardImport
      parentRoute: typeof AppApplayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignInRoute,
  AppRoute.addChildren([
    AppApplayoutRoute.addChildren([AppApplayoutDashboardRoute]),
  ]),
])

/* prettier-ignore-end */
