/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as IndexImport } from './routes/index'
import { Route as AppAImport } from './routes/app/_a'
import { Route as AppALoansIndexImport } from './routes/app/_a.loans/index'
import { Route as AppADashboardIndexImport } from './routes/app/_a.dashboard/index'
import { Route as AppALoansNewImport } from './routes/app/_a.loans/new'

// Create Virtual Routes

const AppImport = createFileRoute('/app')()

// Create/Update Routes

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppARoute = AppAImport.update({
  id: '/_a',
  getParentRoute: () => AppRoute,
} as any)

const AppALoansIndexRoute = AppALoansIndexImport.update({
  path: '/loans/',
  getParentRoute: () => AppARoute,
} as any)

const AppADashboardIndexRoute = AppADashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => AppARoute,
} as any)

const AppALoansNewRoute = AppALoansNewImport.update({
  path: '/loans/new',
  getParentRoute: () => AppARoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/_a': {
      preLoaderRoute: typeof AppAImport
      parentRoute: typeof AppRoute
    }
    '/app/_a/loans/new': {
      preLoaderRoute: typeof AppALoansNewImport
      parentRoute: typeof AppAImport
    }
    '/app/_a/dashboard/': {
      preLoaderRoute: typeof AppADashboardIndexImport
      parentRoute: typeof AppAImport
    }
    '/app/_a/loans/': {
      preLoaderRoute: typeof AppALoansIndexImport
      parentRoute: typeof AppAImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignInRoute,
  AppRoute.addChildren([
    AppARoute.addChildren([
      AppALoansNewRoute,
      AppADashboardIndexRoute,
      AppALoansIndexRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
